### ISSUE TITLE
No idea how to run this? 

### ISSUE THREAD

**Issue by kittentakara** [martynasS/magic-home-desktop#10]
No instructions in read me? 

What do i need to use this? No windows.exe or running instructions or specifications on what is needed to run...

**Comment by SaidTorres3** [comment]
https://github.com/martynasS/magic-home-desktop

At the right, you can see the section "Releases", click on "v0.2 release". Then, download "Magic.Control-0.2.0-win.zip"

When you download it, unzip the file and run the .exe.

**Comment by darshandon3** [comment]
Is there a way where I can code in a different color automatically? Or have it so I can code to change colors accordingly?

**Comment by darshandon3** [comment]
New to this!
