### ISSUE TITLE
Do you need to be on the same network as the led strip to run this

### ISSUE THREAD

**Issue by nmcc1212** [martynasS/magic-home-desktop#11]
### My Network issue

i have a mesh router setup as my main network (tp link deco) but most cheap led controllers don't like mesh networks and don't connect to it. so i bought a cheap router from amazon and use it for these cheap led strips and other iot devices, but all my other devices, such as phone and laptops are on my main network

### The problem

My laptop does not 'discover' my led strip

**Comment by martynaskre** [comment]
Your computer has to be connected to the same network as your Magic Home controllers in order to control your devices.
