### ISSUE TITLE
question about magic home

### ISSUE THREAD

**Issue by kevindevm** [martynasS/magic-home-desktop#17]
so nice app, im very corious about how this work i mean in the code way
- how do you that X device on the network is a magic home device?
- once you got the basic ip, name and mac, how do u turn it on/off/colours/bright?

thanks and sorry i know that it must be in the code but cant find it

**Comment by martynaskre** [comment]
This app under the hood uses [this package](https://www.npmjs.com/package/magic-home) to communicate with Magic Home controllers.
