### ISSUE TITLE
Record Keybind "Stop Recording" button not functioning (macOS 10.15.7)

### ISSUE THREAD

**Issue by dustindmiller** [martynasS/magic-home-desktop#18]

**Comment by martynaskre** [comment]
Did you specify name for the keybind?

**Comment by dustindmiller** [comment]
It won't let me. Once I click record it records the bind and then all the keys I press trying to name it which inadvertently ruins the keybind, and still won't let me stop recording.

**Comment by martynaskre** [comment]
Let me get this clear. You click "Record keybind" button, then you clicked keys for the keybind. After that you should click "Stop recording" button and specify the name of keybind.  If the name was entered button should change to "Save keybind". Did you follow these undocumented steps? 😄

**Comment by dustindmiller** [comment]
Ah, it worked that way. Haha. I think since the "Stop Keybind" button doesn't have any visual cue that it actually stopped (like graying out and saying "Save Krybind" for instance) my brain thought I messed something up and it wasn't working. Thanks!

**Comment by martynaskre** [comment]
No problem, I guess this part needs some sort of visual update. Closing it for now!
