### ISSUE TITLE
Support for us unlucky GRB light owners?

### ISSUE THREAD

**Issue by sofia-valquiria** [martynasS/magic-home-desktop#19]
What it says on the tin. Basically my lights are GRB, not RGB,so the green and red signals are swapped on almost every controller I find. If I were more skilled I 'd modify tho code myself, but oh well. All I can do is politely ask you to consider that small addition <3.

**Comment by martynaskre** [comment]
I think your problem is not within reach of this application. Your problem is related to your LED controller and this app is an interface to manage your controller.
