### ISSUE TITLE
[ENHANCEMENT] - "Ambilight" Option

### ISSUE THREAD

**Issue by MaeseT** [martynasS/magic-home-desktop#22]
**Describe the solution you'd like**

It would be great over the current working base - incredible, thank you -  to have the option of "Ambilight", under my perception would be something like taking the overall -or similar- color shown in the main screen and setting it on the leds. It would be needed to keep refreshing while the option is turned on. 

**Describe alternatives you've considered**
Other alternative, but not as good as the stated above would be to have sort of "eye-dropper" color selector that can take any color on the screen.

**Additional context**

Check it out - https://github.com/dewgenenny/ScreenSync
                       https://youtu.be/izCWz9-xkw4

**Comment by martynaskre** [comment]
Hi! This implementation would require native add ons for MacOS and Windows for the best performance. Currently I don't see this feature on the roadmap, but any help and implementation would be appreciated.

**Comment by MaeseT** [comment]
The user dewgenenny have already implemented it, even a RGB, GRB, BRG option that I saw it was as well requested. (https://github.com/dewgenenny/ScreenSync)
His "on feel" is not that good than the one implemented in here, and he does not have the select color options. I think a merge of both might be quite productive in a relatively short period of time
