### ISSUE TITLE
[ENHANCEMENT] LED visualizer

### ISSUE THREAD

**Issue by Neerolek** [martynasS/magic-home-desktop#23]
I suggest to make some visualizer that the leds change color to the beat of the music or bass. 
It would be good if it listened to the process we choose, e.g. spotify.exe

**Comment by martynaskre** [comment]
Interesting idea :) Do you know any native listening implementations for Windows and Mac?

**Comment by rlolyiyo2** [comment]
I dont know any, but i think you could make one in NodeJS, its pretty hard but i would be glad if you could make it
