### ISSUE TITLE
[BUG] The program is not updated immediately after installation

### ISSUE THREAD

**Issue by AdrKu** [martynasS/magic-home-desktop#28]
100% identical problem as here: https://githubhelp.com/martynaskre/magic-home-desktop/issues/15
I tried to completely delete (via Revo Uninstaller) and reinstall - it still doesn't work. (the early version of the program works)

Computer Information
![image](https://user-images.githubusercontent.com/96945641/147852243-5ea43dae-c8f8-4a2b-b32c-50985213dd1f.png)

Is there already a solution or some kind of workaround for this problem?

**Comment by martynaskre** [comment]
In order to fix this you would have to compile this yourself with commented lines that are mentioned [here](https://github.com/martynaskre/magic-home-desktop/issues/15#issuecomment-828803397).
