### ISSUE TITLE
[ENHANCEMENT] STREAM DECK

### ISSUE THREAD

**Issue by blackcat1101** [martynasS/magic-home-desktop#34]
I would love for there to be a version of this that i can use on my stream deck while in games, as when i use my Alexa i can say mayday mayday mayday and the lights turn red, it would be amazing if we could have preset keys on our stream decks to do it for us. 
**Describe alternatives you've considered**
i have considered setting up a raspberry pi to connect instead of the box and just hosting a web controller from it. and then using an app on my pc to control it, ive thought about using a usb sniffer to make my own control panel from my pc, but then i found this. 

do i have your permission to use your code and make a twitch bot that can control my lights from my pc depending on what the users ether type in chat or if they donate, or if they use channel points to make it strobe or something like that.

**Comment by martynaskre** [comment]
This repo is licensed with MIT license, so you can do whatever you want :)
