### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TonyQJ** [martynasS/magic-home-desktop#38]
**Describe the bug**
The window opens half off-screen. Only the word "Control" is visible in the title bar. The window cannot be dragged on-screen by dragging the title bar. No contextual menu is available when shift-right-clicking the title bar.

**To Reproduce**
1. Click Magic Control on the task bar.

**Expected behavior**
1. App window opens on screen
2. App can be dragged around by clicking on the title bar

**Screenshots**
![MagicControlOffScreen](https://github.com/martynaskre/magic-home-desktop/assets/78753752/d0693790-d060-4592-8bf2-1313f674984f)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
It recently started happening.  No idea why.  i have not changed the screen resolution at any time.

**Comment by martynaskre** [comment]
I see you are using either version `0.1` or `0.2`. Try with version `1.0.0` and let me know if the error persists.

**Comment by TonyQJ** [comment]
That appears to have sorted it Martyn. Thanks.
