### ISSUE TITLE
how to open?

### ISSUE THREAD

**Issue by NetsukiiDev** [martynasS/magic-home-desktop#6]
I have windows 10 but i don't know how to open the app.
Pls help me.
Thanks

**Comment by KenDingel** [comment]
I think you might be trying to download the source code.
You need the compiled exe version, there is a download under "releases" under the "<> Code" Section.
or you can Ctrl+F for "releases". 
Hope this helps!

**Comment by martynaskre** [comment]
@thaAndrex the installer is located in releases. https://github.com/martynasS/magic-home-desktop/releases/
