### ISSUE TITLE
Pull Request: Add Hotkey for Preset Color / Color Preview from Home Screen / Global Dark Mode Setting

### ISSUE THREAD

**Issue by KenDingel** [martynasS/magic-home-desktop#7]
Hello,

I stumbled on your repo earlier today, and I think your work is great! I have a bunch of magic home controlled LEDs, and I've found your code to be exactly what i've been needing. I'd love to contribute.

Here are some ideas, I have and how i'd go about implementing them.
Please let me know if you have more information that might help.

1) Hotkey Colors
- Add a button in the color picking menu picker.vue, to save the current color and brightness. (Possibly up to 5 'presets')
- Add a button to the device.vue, to save an additional hotkey. OR have presets work with '(Hotkey) + (1-5)'.
Plan: 
        Store preset settings into 'store' vue variable. ( store.state.Leds.leds[LEDkey].presets["1-5"] )
        Use hotkey.vue to record additional hotkeys for presets. 

2) Color Preview in Home menu, to the left of the devices name.
- Add an 'icon' that shows the current RGB setting into device.vue
Plan: 
        in device.vue add a css box with the RGB value for each device.

3) Dark Mode Setting
- Add an addition settings button to change background-color for each page to black.
Plan:
       I have this implemented with css styles on each page, set to dark mode.
       This css will be changed from a button in Footer.vue, calling a function to modify the css style of each page.

Looking forward to hearing from you!

**Comment by martynaskre** [comment]
Hi,
these ideas are great and you can surely make the pull request. One thing that I think could be done with dark mode is OS support.

**Comment by martynaskre** [comment]
This has been implemented.
