### ISSUE TITLE
Window key not workinga after install this app

### ISSUE THREAD

**Issue by MrCabana** [martynasS/magic-home-desktop#9]
Hello
This app automates led strip pretty well. The only problem I have  is that my win key and the popup menu key stopped working after installing this app.
How can I have these keys working again?
Thanks for the great job.

**Comment by martynaskre** [comment]
Hi, maybe you added a keybind on these keys?

**Comment by TonyQJ** [comment]
Win10, latest update. Keybind doesn't work at all for me. I chose Ctrl+# and that combination does nothing.  I changed it to m+# - still nothing.

**Comment by TonyQJ** [comment]
Okay, it's something to do with those keys. If I change the bind to Ctrl+Backspace it works. Bug?

FWIW - UK Keyboard with UK settings.

**Comment by martynaskre** [comment]
I dont have any tools how to reproduce that so I'm closing it.
